//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.10 at 07:18:30 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://model.tks.edu.com/record", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.edu.tks.model.record;
