version: "3.9"
services:
        zookeeper:
                image: "bitnami/zookeeper:latest"
                container_name: "myapp-zookeeper"
                networks:
                        test-net:
                                ipv4_address: 172.44.0.89
                ports:
                - "2181:2181"
                environment:
                - ALLOW_ANONYMOUS_LOGIN=yes

        # See:
        # https://hub.docker.com/r/bitnami/kafka
        kafka:
                image: bitnami/kafka:latest
                container_name: "myapp-kafka"
                networks:
                        test-net:
                                ipv4_address: 172.44.0.88
                ports:
                - "9092:9092"
                environment:
                - KAFKA_BROKER_ID=1
                - KAFKA_LISTENERS=PLAINTEXT://:9092
                # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.5.0.1:9092
                - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
                - ALLOW_PLAINTEXT_LISTENER=yes
                depends_on:
                - zookeeper
        userservice:
                image: tks/userservice:latest
                container_name: userservice
                hostname: userservice
                networks:
                        test-net:
                                ipv4_address: 172.44.0.3
                expose:
                        - 8080
                ports:
                        - "8080:8080"
        # recordservice:
        #         image: tks/recordservice:latest
        #         container_name: recordservice
        #         hostname: recordservice
        #         networks:
        #                 test-net:
        #                         ipv4_address: 172.44.0.4
        #         expose:
        #                 - 8080
        #         ports:
        #                 - "8081:8080"
        # gateway:
        #         image: tks/gateway:latest
        #         container_name: gateway
        #         hostname: gateway
        #         networks:
        #                 test-net:
        #                         ipv4_address: 172.44.0.10
        #         expose:
        #                 -       8080
        #         ports:
        #                 -       "5555:8080"
        # eureka:
        #         image: tks/eureka:latest
        #         container_name: eureka
        #         hostname: eureka
        #         networks:
        #                 test-net:
        #                         ipv4_address: 172.44.0.99
        #         expose:
        #                 - 8761
        #         ports:
        #                 - "8761:8761"
networks:
  test-net:
    ipam:
      driver: default
      config:
        - subnet: 172.44.0.0/24