eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://172.44.0.99:8761/eureka"
  instance:
    prefer-ip-address: true
spring:
  cloud:
    inetutils:
      timeout-seconds: 5
    function:
      definition: consumer;producer
    stream:
      bindings:
        producer-out-0:
          destination: confirm-topic
          producer:
            useNativeEncoding: true
        consumer-in-0:
          destination: add-topic
          consumer:
            useNativeDecoding: true
      kafka:
        binder:
          brokers: 172.44.0.88:9092
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: com.edu.tks.service.client.MessageSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.edu.tks.service.client.MessageDeSerializer
  application:
    name: recordservice
management:
  endpoint:
    beans:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"